---
title: "discussion 11"
author: "Victor Torres"
date: "2024-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task.

## Your task is to analyze an existing recommender system that you find interesting. You should:

### 1. Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

#### First I would like to dive into the definition of a recommender system, a recommender system is an artificial intelligence or AI algorithm, usually associated with machine learning, that uses Big Data to suggest or recommend additional products to consumers. These can be based on various criteria, including past purchases, search history, demographic information, and other factors. Recommender systems are highly useful as they help users discover products and services they might otherwise have not found on their own. There are several types of techniques used for recommender systems, some of them are collaborative, content, and hybrid systems filtering.

#### I decided to perform an scenario design on Uber eats, which is an app that I use quite a lot, Uber Eats has thousands of restaurants and food type to choose from.The application allow us to keep track of the delivery, including the timeline of the preparation, name of the person who is delivering the goods, and online payments including tips and rate the food and service provided by the merchant.In addition, you can preset your favorite deliveries spots, to save time when you ready to order. The target audience is huge, so Uber eats needs to fulfill their needs by providing a vast variety of food types, as well as restaurants and delivery personnel that ensures proper delivery timelines to their customers, which is Uber eats key goals.

#### In order to meet their goals, Uber eats uses a machine learning system called "Michelangelo", with a focus on Two-Tower Embeddings (TTE)₂." These embeddings create a magical experience by helping customers find what they’re looking for faster and easier. Specifically, we focused on the modeling and infrastructure to build out Uber’s first TTE model. We then used that to power our recommendation systems by generating and applying embeddings for eaters and stores." (Ling, 2023).

### 2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

#### In order to attemp reverse engineer in this recommender system, I might need to combine Uber eats databases that contains customer's, restaurant's, and providers(delivery personnel) information, to create a data model with recommendations of food items or restaurants based on repeated orders, neighborhood, and cultural background, one of the strategies that I might use to succesfully achieve these goals is by filtering ratings of users, and also preset a customers profile with favorite food types and restaurants. Uber Eats recommendation system has two sub-systems, one is for of food that helps give context and categorization of all the food items, and the second one helps aquire the ranks of food quality, reataurants, and deliveries. That would make easier to achieve reverse engineer in thids scenario.

### 3. Include specific recommendations about how to improve the site's recommendation capabilities going forward. 

#### My recommendations to improve the site's capabilities would be to create a  personalization system, Users should be able to select items on restaurant menu based on diet preferences, check and change the amount of calories on plates, being able to select the delivery person based on personal experience, preset health conditions such as alergies, also other social factors such as religion, and nationality to help the system to narrow down the recommendations to the user.

# Conclussion.

### After performing a system analisys to the Uber eats recommender system, I realized the these systems are vital for companies and organizations, to provided a better service for their customers. Big companies such as Amazon, Uber, Google, etc. spends millions of dollars in research of how improve their systems, and they are always updating their AI machine learning systems to achieve their goals. It was a great experince to research about this topic, and to get a better understanding of how recommender systems works.

## References.

#### Ling, B., & Melissa Barr. (2023, July 26). Innovative recommendation applications using two tower embeddings at Uber | Uber Blog. Innovative Recommendation Applications Using Two Tower Embeddings at Uber. https://www.uber.com/blog/innovative-recommendation-applications-using-two-tower-embeddings/ 

#### What is a recommendation system?. NVIDIA Data Science Glossary. (n.d.). https://www.nvidia.com/en-us/glossary/recommendation-system/

